Remove harvester validator in pre-delete
Signed-off-by: Jian Wang <jian.wang@suse.com>
(cherry picked from commit 099cec504fb1f611df7d5293149026ee4d20d44f)

diff --git a/deploy/charts/harvester/templates/job.yaml b/deploy/charts/harvester/templates/job.yaml
--- a/deploy/charts/harvester/templates/job.yaml
+++ b/deploy/charts/harvester/templates/job.yaml
@@ -66,6 +66,8 @@ spec:
               echo '[INFO] deleting kubevirt ...';
               kubectl delete kubevirt --wait --all;
               {{ end }}
+              echo 'delete harvester webhooks harvester-validator'
+              kubectl delete ValidatingWebhookConfiguration -n harvester-system harvester-validator --force || echo 'kubectl failed'
               exit
 {{- if .Values.jobs.preDelete.containers.kubectl.resources }}
           resources:
